name: Go

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Download dependencies
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4f58623b88e35c8172c05b70ed3b93ee8a1bfdd1 # v8
        with:
          version: v2.1
        continue-on-error: true

      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@8b4478c7019be847373babde9300210e7de34bfb # v2.2.0
        with:
          version: 'v2.5.0'

      - name: Run tests against in-memory implementation
        run: |
          set -euo pipefail
          go test -count 1 -json -v . 2>&1 | tee /tmp/test-memory.json | gotestfmt
        continue-on-error: true

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@2941118d7ef622b1b3771d1ff6eae9e90659eb26 # v0.8.0
        with:
          test-results: /tmp/test-memory.json

      - name: Run DynamoDB local
        run: |
          docker run --detach --publish 8000:8000 amazon/dynamodb-local:2.6.1
          # Wait for container to be ready. From https://stackoverflow.com/a/77373799:
          attempt=0
          while [ "$attempt" -lt 10 ]; do
            status=$(curl -s -o /dev/null -I -w '%{http_code}' http://localhost:8000 || true)
            echo "attempt $attempt, status: $status"
            if [ "$status" -eq "400" ]; then
              exit 0;
            fi
            sleep 1
            attempt=$(( attempt + 1 ))
          done
        timeout-minutes: 1

      - name: Run main tests against DynamoDB local
        env:
          DYNAMODB_ENDPOINT: http://localhost:8000
        run: |
          set -euo pipefail
          go test -count 1 -json -v . 2>&1 | tee /tmp/test-ddblocal.json | gotestfmt

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@2941118d7ef622b1b3771d1ff6eae9e90659eb26 # v0.8.0
        with:
          test-results: /tmp/test-ddblocal.json



